query_scivision_catalog.ipynb, scivision/catalog/__init__.py, scivision/catalog/catalog.py
This PR adds:
* return an empty list for an empty query
* `catalog.keys()` the valid (searchable) keys from the database
* `catalog.values(key)` - the unique values in the database for a valid `key`
* updated example notebook
=> add extra query functionality

.github/workflows/scivision.yml, scivision/io/__init__.py, scivision/io/reader.py, tests/test_reader.py, tests/test_scivision.yml
Changes:
1. Update `load_pretrained_model` so that it accepts just the model repo url and knows to look for `scivision.yml`, or accepts a full path, including local.
2. Add `load_dataset` which takes a repo with an intake catalog, also called `scivision.yml`, or accepts a full path, including local.
3. Tests 2.
Closes #73 
This was a todo, now created a separate issue:
- Add tests for other functions in `reader.py` -> #79
=> Add load_dataset function

contributing.md, setup.py
Addresses @AidaMehonic's comment on [this PR](https://github.com/alan-turing-institute/scivision/pull/56)
=> Use scivision@turing.ac.uk as contact email

README.md, docs/api.rst, docs/conf.py
Updated how to update/maintain everything on the main README and added the `reader.py` functions to the API page of readthedocs.
Once I hit the build button after this PR gets merged, the docs will look like the below, which are auto-generated from the docstrings. I think at the moment I'll hold off on adding any other functions since they aren't user facing
=> Readthedocs API and repo README updates

README.md, readthedocs_requirements.txt, scivision/io/reader.py
see PR title^
Weirdly I had to install an extra package called `m2r2` to build the docs which I didn't need to before... unsure why
Change to API doc:
=> Add link to intake docs & update readthedocs requirements

examples/mapreader_plant_scivision.ipynb
Closes #171 
- Added `installation` section in: https://github.com/alan-turing-institute/mapreader-plant-scivision
- Updated notebook so that it first install all required libraries
@evangeline-corcoran Could you please take a look at this?
=> Notebook: MapReader to classify plant patches

scivision/catalog/data/datasources.json
This PR refers to add the Plankton sample dataset from a [YAML file](https://github.com/alan-turing-institute/plankton-cefas-scivision). 
I am not sure which is the purpose of the field `labels`. However, for the Plankton dataset I left the default value `True` as  the class can be inferred from the filename.
=> add plankton dataset

scivision/catalog/catalog.py, scivision/catalog/data/datasources.json, scivision/catalog/data/models.json
This PR refers to add the [resnet-50 cefas model plugin](https://github.com/alan-turing-institute/plankton-cefas-scivision) for classifying plankton images. 
Note I added multiple elements in the `institution` field.
=> Add resnet-50 cefas model to scivision catalog

scivision/catalog/data/models.json
This PR refers to add the [vedge detector model plugin](https://github.com/MartinSJRogers/VEdge_Detector/tree/scivision) for automated detection of coastal vegetation edges in remote sensing imagery.
Some observations: 
- The plugin is in the `scivision` branch instead of `main`.
- The model only works with `python=3.7`
=> add vedge detector model

scivision/catalog/data/models.json
This PR fixes the name of the vedge detector model in the scivision model catalog.
=> fix misspelling in name for vedge detector model

docs/maintainers.md, setup.py
scivision 0.1.3 has been released at https://pypi.org/project/scivision/
This PR updates the version number on GitHub and makes some minor changes to docs
=> Release scivision 0.1.3

.github/workflows/publish-to-pypi.yml, docs/maintainers.md
- Closes #86 
- Adds PyPI publishing job to GH actions: tagged commits will initiate a new release
- Tags a commit with `0.2.0` to test this, so should close #199 
- Updates the readthedocs
=> Automate PyPI upload

.github/workflows/publish-to-pypi.yml
Reverts alan-turing-institute/scivision#210
Ok I misunderstood this - I think `@master` is the branch of the GH action, not the scivision repo, so it should not be `@main`
=> Revert "Use main branch, not master for PyPI release GH actions"

scivision/catalog/data/models.json, setup.py
I've created a new plugin, directly inspired by @quantumjot's original one (and some code borrowed), which enables loading of any model from https://pypi.org/project/image-classifiers/ via the scivision interface and provides a rudimentary predict function: https://github.com/alan-turing-institute/scivision_classifier 
We could take a similar approach for other packages/frameworks without too much effort, see #218
Some manual effort was required to fit the repo to the scivision specification (see how I had to add each model name to 3 places: model.py, model.yml & __init__.py !), but this might not be something we need to worry about too much if we only want to add an entire package/framework's model selections to scivision for a few select cases.
Interested to hear people's thoughts on …
=> Add image-classifiers models repo to catalog

environment.yml, examples/README.md, scivision/catalog/data/datasources.json, scivision/io/installer.py
1. Closes #221 by adding a `_reinstall` function: when you do `load_pretrained_model('path/to/repo', allow_install=True)`, it will reinstall it when running a second time, but not when allow_install=False
2. Edits the Koala catalog entry so it matches on the "classification" task, so it appears in results when using `scivision_classifier` models (see `models.json`)
3. Updates instructions for running example notebook locally - it wasn't clear already that you'd need to have the environment in the `environment.yml` built/activated, which installs `intake-xarray` via conda-forge (the binder version does this)
=> Add reinstall step

scivision/io/installer.py
This PR is a follow-up to #223.
Uses `pip install --force-reinstall --no-cache-dir` to force reinstallation of a package if `install_package` is called with `allow_install='force'`.
Considered passing these options by default in `_install`, and always calling `install_package`, but this can be unreasonably slow (--no-deps as in #223 is faster, but will sometimes result in dependencies not getting correctly updated).
@edwardchalstrey1 does this approach address the original issue (#221)?
No test for use of this option, since it can add a lot of time (using it with `test_load_pretrained_model_local` takes almost 2 minutes).
=> Add 'force' option to allow_install

scivision/io/installer.py
=> Remove type hints in installer ('Literal' unsupported in python 3.7)

CODE_OF_CONDUCT.md, scivision/catalog/data/datasources.json, scivision/catalog/data/models.json
This PR refers to add the [detectreeRGB model plugin](https://github.com/acocac/detectreeRGB-treecrown-scivision) (temporalily hosted in my personal GH repo) to predict the location and extent of tree crowns from a top-down RGB image, captured by drone, aircraft or satellite
Some observations:
The model repository will be transfered to the model developer, @shmh40
The model works with python=3.8
=> [CAT] Add detectreeRGB model and data

scivision/io/reader.py, setup.py, tests/test_reader.py
Closes #340 
Will affect any examples that use `load_pretrained_model` with the `model` arg (now `model_selection`) which should only be example notebooks set up by @edwardchalstrey1 - not any of the project notebooks in https://github.com/scivision-gallery/
=> Rename model arg in load_pretrained_model to model_selection

docs/data_repository_template.md, docs/model_repository_template.md
Fixes #332 (and a couple of additional links).
Assumes that we're only building to html (difficult to fix in the general case with the current mixed md/rst structure)
=> Fix some broken internal links in docs

README.md
Changing to >=0.3, since we haven't tested with the older versions and which were known not to work at some point.
=> Update supported scivision version for python 3.10

frontend/src/App.js
It seems I didn't check the mobile nav properly in my last PR. 😬
When a nav item is clicked in the mobile nav, it should collapse the Navbar, bring it back to its closed position. 
But react-bootstrap being made for SPA, `collapseOnSelect` attribute on the Navbar does not work well with react-router. 
The discussions in the react-boostrap recommends installing the [react-router-boostrap]( https://github.com/react-bootstrap/react-router-bootstrap) package, which requires wrapping all the router links(including the Nav links) with a new `<LinkContainer>` bootstrap element for all router links to work perfectly. 
This PR fixes that with a workaround as I don't think currently there is a need to use `<LinkContainer>` for all the router links as everything else seems to be working fine.
But if …
=> Bug fix: Mobile nav collapse 

scivision/io/installer.py
Currently if `allow_install=True`, the package, and it's dependencies, will be force reinstalled. However, this can have unintended consequence. The current issue I have noticed is that even if all the requirements are already satisfied, installing the model will reinstall these required packages. 
This relates to #223, #249, #253
=> Separating force reinstall from package installation

tests/test_reader.py
Closes #578.
This test currently fails but the error is external to scivision.
The corresponding catalogue entry should eventually get picked up by automated checks (although not yet).
=> Remove test that depends on a third-party API

.github/workflows/scivision.yml, setup.py
This PR includes:
- #588
- #589
It fixes #587
Note: the previous branch protection rules, checking that the build passed, depended on the names of the checks from the build matrix.  #588 changes these (it now includes the OS), but introduces a single check `all-builds-passing`.  The branch protection rule for main has been updated, but open PRs will need to include this change to work.
=> Windows fixes

README.md, setup.py
Change Scivision banner image source from `imgs/logo_name.png?raw=true)` (which breaks in PyPI) to `imgs/logo_name.png` for release 0.6.1 to attempt to fix this.
=> Fix image location in README.md

README.md, setup.py
Relase 0.6.2: Attempt to fix broken image on PyPI (#607 didn't work)
=> Use absolute URL for Scivision logo in README

requirements.txt
This loosens the requirement on the pandas version (2.0 was released in April).
None of the [breaking changes](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#backwards-incompatible-api-changes) from v1.0 affects scivision.
Closes #593
=> Bump pandas version

docs/user_guide.md
The PR add a new section in the documentation explaining how to install `cloud_extra` optional dependencies in scivision.
Fixes #641 
* A new section 🔗 Optional dependencies
=> Add optional dependencies

docs/contributing.md, docs/data_repository_template.md, docs/model_repository_template.md, frontend/src/DatasourceNew.jsx, frontend/src/ModelNew.jsx, frontend/src/ProjectNew.jsx
Aims to address #643 
When trying to contribute a object to the catalog through the form on the front end, an error was occurring (see #643). The issue was as a result of an incorrect file path to the catalog. 
* Correcting the file path to the catalog in the ModelNew.jsx, ProjectsNew.jsx and DatasourceNew.jsx files
* Also addressing other places where this incorrect file path appeared in the documentation
=> Correcting file path for the catalog when adding a new object

README.md, frontend/src/ScivisionPy.jsx
The example python code on the website / in the readme had a couple of typos that means it wasn't running. These are now corrected.
=> Correcting typos in the example python code
