alan-turing-institute/scivision

- .github/workflows/scivision.yml
- dev/validate_catalogs.py
This adds a utility function that will validate JSON files on PR or push
> update workflow to automatically validate JSON files

- .github/workflows/scivision.yml
Adds a pytest action. 
Should wait until #43 and #15 are merged until we merge this.
Closes #29
> Update github workflow to include pytest

- README.md
Thanks for integrating the PR!
I thought it would be nice to display the status of both CI and docs in the readme as well.
> Add CI and docs badge status

- dev/datasources.json
> Reference plankton intake driver within the datasources catalogue

- scivision/catalog/catalog.py
> ```tags``` are incorrectly read as a string

- MANIFEST.in
- setup.py
Changes needed to push to pypi
> 0.1.1 release

- README.md
Proposed to offer users a ready-to-go interactive jupyter notebook session through binder (https://mybinder.org/).
> Add "run in binder" badge

- README.md
- postBuild
> Fix failing notebook example in Binder

- docs/requirements.txt
https://github.com/alan-turing-institute/scivision/issues/53#issuecomment-1016486773
> Add project requirements to doc requirements

- examples/mapreader_plant_scivision.ipynb
Closes: https://github.com/alan-turing-institute/scivision/issues/150
> [WIP] Model inference using a pretrained MapReader model

- contributing.md
- Updates the docs to reflect the current process of adding entries to the scivision catalog inside this repo
- Rearranges existing guidelines
- Adds a placeholder link for #89
> Make contribution guidelines into more informative how-to doc

- scivision/catalog/data/models.json
add early version of mapreader for plants model to model catalog from model repro https://github.com/alan-turing-institute/mapreader-plant-scivision
> add mapreader for plants to model catalog

- docs/api.rst
- docs/index.rst
- scivision/catalog/catalog.py
> Update API docs with catalog functions

- setup.py
- tests/test_reader.py
Simply increment the version no. in `setup.py`
(I will create a separate PR updating the docs to reflect these steps later)
Also removes a bad test
> Increment version to 0.2.3 (testing automated PyPI release)

- docs/maintainers.md
Close #86 properly and document process
> Refine release instructions

- setup.py
Some recent PRs with catalog additions have not been pushed to pypi
> Increment version for new pypi release

- setup.py
> Bump version to 0.2.7 and remove requirement

- .github/workflows/scivision.yml
~New PR since checks failed to report in #270~ (Updating the branch protection rules fixed this)
> Run scivision CI with several python versions

- scivision/catalog/catalog.py
> Validate that the 'name' catalog fields are distinct

- scivision/io/autoplumber.py
> Rename config file in error msg

- contributing.md
Cherry-picked contributing guide changes from #226
> Update contributing guide

- frontend/README.md
- frontend/package.json
Changes:
1. README
2. add `react-bootstrap` (I chose v1 because we are using v4.x of bootstrap [see here](https://www.npmjs.com/package/react-bootstrap))
Other issues:
- ~~`App.js` doesn't currently import the actual catalog, it's from a copy stored in `frontend/src`, we should update this to link to the actual catalog, my basic attempt fails`~~ I created a separate issue for this #353
> Frontend required changes to work

- .github/workflows/scivision.yml
- README.md
- Updates CI to run on Python 3.10
- Adjusts the supported versions table as per how we see scivision/Python currently working
> Make supported versions table clearer

- .github/workflows/frontend.yml
- frontend/package-lock.json
@ots22 will this fix [this problem](https://github.com/alan-turing-institute/scivision/pull/398#issuecomment-1318369850)?
Oh I see `npm ci` is supposed to be an alternative to `npm install`...
> Make sure npm install is run on push to main

- setup.py
This will get changes to model names in #477 on PyPI
> Bump scivision version to 0.5.0

- frontend/public/index.html
- frontend/public/manifest.json
This PR fixes #496 by add meta description to the frontend webapp.
> Add meta description to frontend

- README.md
The logo in the README.md file still uses a remote URL instead of local. 
Reviewers, please check if the size is ok.
> [ENH] Update logo in README.md

- scivision/io/installer.py
> Separating force reinstall from package installation

- frontend/src/App.css
The PR aims to replace yellow background for Discover/Explore more text.
> Change Colour Discover/Read more messages in Front-end

- frontend/src/App.js
Embedding: https://www.youtube.com/watch?v=B7fOBpXnO4g
Issue: [#523](https://github.com/alan-turing-institute/scivision/issues/523)
> Embed video on the about page

- tests/test_reader.py
- tests/test_wrapper.py
> Use isinstance instead of comparing types for equality

- scivision/catalog/data/datasources.json
> Add FathomNet23 dataset to datasources.json

- setup.py
Increment version number in preparation for release
> Update setup.py for release 0.6

- frontend/src/App.css
- frontend/src/App.js
- frontend/src/Community.js
- frontend/src/ScivisionPy.js
- frontend/src/about.js
Make a CSS class (`text-block`) for controlling the width of long-form text on the website, set this to 62 characters, and apply it to tabs containing text.
> Text width

- pyproject.toml
Fixes #625. It should work after MR #635.
* Add optional dependencies groups to support data stored in commercial cloud storage.
> Add optional cloud dependencies

- src/scivision/catalog/data/models.json
This is an automated message from the Scivision frontend (https://sci.vision):
> Your submission was successful and will be reviewed by the Scivision 
> maintainers before being added to the catalog, thank you.  If we have any
> questions about your submission we will post them here.
> Add "StarDist Seed" to the model catalog

- README.md
- frontend/src/About.jsx
- frontend/src/ScivisionPy.jsx
On the About page, listing the scivision tools, pixelflow and scivision.py, as well as adding a hyperlink to the Turing webpage.
On the Scivision.Py page, adding a link to the scivision github repo
> Minor updates to the website text

- .github/workflows/publish-to-pypi.yml
The master branch has been sunset
> Change pypa/gh-action-pypi-publish from @master to @release/v1

- src/scivision/catalog/data/models.json
This is an automated message from the Scivision frontend (https://sci.vision):
> Your submission was successful and will be reviewed by the Scivision 
> maintainers before being added to the catalog, thank you.  If we have any
> questions about your submission we will post them here.
> Add "canopy-quality" to the model catalog

- frontend/src/Contribute.jsx
- frontend/src/DatasourceNew.jsx
- frontend/src/ModelNew.jsx
- frontend/src/ProjectNew.jsx
> Aldenc patch 2

- README.md
- docs/contributing.md
- docs/data_repository_template.md
- docs/index.rst
- docs/model_repository_template.md
- docs/scip/0001-model-dependencies.md
- docs/user_guide.md
- frontend/src/About.jsx
- frontend/src/Community.jsx
- frontend/src/Contribute.jsx
- frontend/src/DatasourceNew.jsx
- frontend/src/Home.jsx
- frontend/src/ModelNew.jsx
- frontend/src/ProjectNew.jsx
updating various text and documentation fixes for clarity and consistency!
> Aldenc patch 1

- .github/workflows/frontend.yml
> Update folder name

- docs/contributing.md
- docs/data_repository_template.md
- docs/model_repository_template.md
- docs/user_guide.md
- frontend/src/components/CatalogEntryForm.jsx
- frontend/src/pages/DatasourceNew.jsx
- frontend/src/pages/ModelNew.jsx
- frontend/src/pages/ProjectNew.jsx
> I fenton editing

- .github/workflows/check-catalogs.yml
- .github/workflows/check-models.yml
- .github/workflows/frontend.yml
Updating website to run off the branch catalog-validation. This allows the validation artefacts to be created without issues of a protected main branch
> Catalog validation

- .github/workflows/check-catalogs.yml
- .github/workflows/check-models.yml
- .github/workflows/frontend.yml
* Updating to run on separate branch
* Updating to run on separate branch
* fixing error with git pull
> Catalog validation (#704)

- pyproject.toml
> Update project version for a new release

- .github/workflows/frontend.yml
> Update frontend.yml to run only on main

- .github/workflows/frontend.yml
Making sure the model / data checks are updated regularly
> Add a chron schedule

- src/scivision/catalog/catalog.py
> Correcting typo
